# Generated by Django 5.0.4 on 2024-04-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name'], name='store_cusom_first_n_8687cd_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_cusomers',
        ),
    ]
