# Generated by Django 5.0.4 on 2024-04-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_fist_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_cusom_first_n_8687cd_idx',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['given_name', 'last_name'], name='store_cusom_given_n_fbacc6_idx'),
        ),
    ]
