# Generated by Django 5.0.4 on 2024-04-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_customer_store_cusom_first_n_8687cd_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_cusom_given_n_8dfeb9_idx',
            old_name='store_cusom_given_n_fbacc6_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_cusomer',
        ),
    ]
