# Generated by Django 5.0.4 on 2024-04-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_store_cusom_given_n_fbacc6_idx_store_cusom_given_n_8dfeb9_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
        """
            INSERT INTO store_collection (title)
            VALUES ('collection_01')                  
        """,
        """
            DELETE FROM store_collection
            WHERE title='collection_01'
        """
        )
    ]
