# Generated by Django 5.0.4 on 2024-04-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20240429_2151'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_given_n_228977_idx',
            old_name='store_cusom_given_n_8dfeb9_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
